---
title: "PB4A7 - Quantitative Applications for Behavioural Science"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# 📑 Course Brief

**Description:** 
In this course, students will immerse themselves in the world of causal inference methodologies, a cornerstone in behavioural science research. The curriculum guides learners through the essential processes of cleaning, analysing, and visualising secondary data, equipping them with the skills to conduct robust and insightful research. Through practical examples, students will learn to adeptly navigate various research designs, and develop the proficiency to communicate their findings effectively, fostering a deeper understanding and application of best practices in behavioural science.


**Focus:** Understand the fundamentals of causal inference and its applications in Behavioural Science. Master statistical tools used by psychologists, political scientists, and economists. Recognize and address contemporary issues in behavioural science.

**Download the full syllabus [here](https://lse-main-mdl-euwest1.s3.eu-west-1.amazonaws.com/1f/c6/1fc6b1a781e052d5c85277c9563638823caa896e?response-content-disposition=inline%3B%20filename%3D%22PB4A7_Syllabus_2023_24.pdf%22&response-content-type=application%2Fpdf&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIARJMQYW4LM5PB3ZM2%2F20230920%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20230920T104544Z&X-Amz-SignedHeaders=host&X-Amz-Expires=21556&X-Amz-Signature=ccd2b1ae4e93b803b35d9b7bb20e93854f3e5c730d7f4fc4dc2c6d026b3aac82)**

🛠️ **Requirements:** For students who have no prior experience with statistics and/or STATA, the completion of the following Digital Skills class is highly recommended:

[Introduction to STATA](https://moodle.lse.ac.uk/course/view.php?id=7882)

# 🎯 Learning Objectives

- How to distinguish **Causation** from Correlation
- How different research designs work
- How to apply different research designs on _Stata_
- How to effectively visualise your findings



-----------------

<a href="2023/index.qmd">
    <button class="button-61"> Enter the class</button>
</a>

