---
title: "<font style='font-size:1em;'>💻 Seminar 3<br/> Hypothesis testing & OLS</font>"
author: Dr. [George Melios](#)
institute: '[London School of Economics and Political Science](#)'
date: 10 October 2023
date-meta: 10 October 2023
date-format: "DD MMM YYYY"
toc: true
toc-depth: 1
toc-title: "What we will cover today:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs: 
    fig-responsive: true
    theme: simple
    slide-number: true
    mouse-wheel: false
    preview-links: auto
    logo: /figures/logos/MY_INSTITUTION.png
    css: /css/styles_slides.css
    footer: 'PB4A7- Quantitative Applications for Behavioural Science'
---

# OLS 

## OLS

- During this seminar:
    -	We will go through Seminar 2 & 3 exercises. 
    - Please conduct your analyses on your do-files and keep a log-file.
    - See how we can run OLS on STATA and test hypotheses


---

## Tasks

1.	Regress education on yearsexp. Interpret the coefficient. What does the result tell us?

2.	Create a set of dummy variables to capture the different levels of education on yearsexp. 

---

## Tasks

3.	Test the null hypothesis that there is no effect of earning a college degree on yearsexp using an OLS regression model. State the alternate hypothesis.  
    a.	Interpret the estimated coefficient. 
    b.	Based on the results, do you reject the null hypothesis? Explain using t-statistic, p-values and confidence intervals. 
    c.	What is the prediction for an applicant who has not earned a a college degree? 
    d.	What is the prediction for an applicant who has earned a a college degree? 

---

## Tasks

4.	Test the null hypothesis that there is no effect of earning a college degree on yearsexp using an OLS regression model using robust Standard Errors. Do the coefficient values change? 

5.	Test the null hypothesis that there is no effect of earning a college degree on yearsexp using ANOVA.
